---

slack:
  token: <token>
  bot_user: <bot user>
  channels:
    chanel1: <chanel1 id>
    channe2: <channel2 id>
  messages:
    greeting_message: |
                      Hi, I'm bitbot :bitlogo: . This is our first community coding project!
                      Join in on the fun!
                      Hack all the things :neckbeard:!
                      Drink all the :beer:!
    another_message: |
                     A differnt message to post.
